version: '3.5'

services:
  mad_app:
    container_name: mad_app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    image: ildarthegreat/red-mad-robot-testtask:latest
  postgres:
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=password
      - POSTGRES_USER=password
      - POSTGRES_PASSWORD=password
    image: postgres:latest
  openapi:
    container_name: openapi
    ports:
      - "80:8080"
    environment:
      - SWAGGER_JSON_URL=https://raw.githubusercontent.com/IldarGreat/RedMadRobotTest/main/src/main/resources/openapi_bulletin_board.yml
    image: swaggerapi/swagger-ui:latest
