spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true

application:
  auth:
    jwt-secret: "RedMadRobot"
    jwt-expiration-time: 1h
    cookie-name: "SESSION"

