spring:
  liquibase:
    enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/robots
    username: root
    password: admin
  jpa:
    generate-ddl: true
    show-sql: true

application:
  auth:
    jwt-secret: "RedMadRobot"
    jwt-expiration-time: 1h
    cookie-name: "SESSION"

