spring:
  liquibase:
    enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/password
    username: password
    password: password
  jpa:
    generate-ddl: true
    show-sql: true

application:
  auth:
    jwt-secret: "RedMadRobot"
    jwt-expiration-time: 1h
    cookie-name: "SESSION"

